#!/usr/bin/env bash
# Sets the PATH environment variable to add the following values, in this
# order:
#
# 1. The `bpm/.bin` folder in the current directory or the first parent that
#    contains a `bpm.ini` file.
# 2. The user's `~/.bpm/.bin` folder.
# 3. The system's `/usr/lib/bpm/.bin` folder.
# 4. The rest of the existing PATH.
#
# To accomplish this, we simply work backwards and prepend new paths.
#
# Returns nothing.
bpm::addLocationsToPath() {
    local ini

    # Add the system location
    bpm::prependToPath /usr/lib/bpm/.bin "global libraries"
    bpm::prependToPath ~/.bpm-modules/.bin "user libraries"
    bpm::findParentIni ini

    if [[ -n "$ini" ]]; then
        bpm::prependToPath "${ini%/*}/bpm-modules/.bin" "project libraries"
    fi
}
