#!/usr/bin/env bash

# Downloads a package from the package registry.
#
# $1 - Library directory for installation.
# $2 - Package name.
# $3 - Package version specifier.
#
# Returns true (0) on success. Returns 1 when there is a strange error, such
# as not being able to make a folder. Returns 2 if there's a download problem.
# Returns 3 if the archive can not be expanded.
bpm::downloadPackageFromHttp() {
    local dest

    dest="$1/$2"
    mkdir -p "$dest" || return 1
    log::debug "Downloading: $3"
    bpm::getUrl "$3" > "$dest/.bpm-archive" || return 2
    bpm::expandArchive "$dest" ".bpm-archive" || return 3
    rm "$dest/.bpm-archive" || return 1
    bpm::fixPackageNesting "$1/$2"
}
