#!/usr/bin/env bash

# Use the version specifier and download or copy the files into the modules
# folder.
#
# $1 - Library directory for installation.
# $2 - Package name.
# $3 - Package version specifier.
#
# Returns true (0) on success. Returns 1 if there was any problem that's
# a file system level (can't make a directory, can't copy a file). Returns
# 2 if the package could not be downloaded or if the download method is
# unable to be determined. Returns 3 if the archive could not be expanded or
# if there is invalid library information encountered.
bpm::downloadPackage() {
    if [[ "$3" == "*" ]]; then
        bpm::downloadPackageFromRegistry "$1" "$2" "$3"
    elif [[ -d "$3" ]]; then
        bpm::downloadPackageFromDirectory "$1" "$2" "$3"
    elif [[ -f "$3" ]]; then
        bpm::downloadPackageFromFile "$1" "$2" "$3"
    elif [[ "$3" == *://* ]]; then
        bpm::downloadPackageFromHttp "$1" "$2" "$3"
    else
        log::error "Unable to download package $2: $3"
        log::error "No known method of download."

        return 2
    fi
}
