#!/usr/bin/env bash

# Downloads a package from a given archive file.
#
# $1 - Library directory for installation.
# $2 - Package name.
# $3 - Package version specifier.
#
# Returns true (0) on success. Returns 1 when the archive format can not be
# determined.
bpm::downloadPackageFromArchive() {
    local dest tempFile

    dest="$1/$2"
    cp "$3" "$dest/.bpm-archive"
    mkdir -p "$dest"

    case "$2" in
        *.tar)
            log::debug "Untar: $3"
            tempFile="bpm-archive-$$.tar"
            (
                cp "$3" "$dest/$tempFile"
                cd "$dest"
                tar xf "$tempFile"
            )
            ;;

        *.tar.bz2)
            log::debug "Untar and bunzip2: $3"
            tempFile="bpm-archive-$$.tar.bz2"
            (
                cp "$3" "$dest/$tempFile"
                cd "$dest"
                tar xfj "$tempFile"
            )
            ;;

        *.tar.gz|*.tgz)
            log::debug "Untar and gunzip: $3"
            tempFile="bpm-archive-$$.tar.gz"
            (
                cp "$3" "$dest/$tempFile"
                cd "$dest"
                tar xfz "$tempFile"
            )
            ;;

        *.zip)
            log::debug "Unzip: $3"
            tempFile="bpm-archive-$$.zip"
            (
                cp "$3" "$dest/$tempFile"
                cd "$dest"
                unzip -qq "$tempFile"
            )
            ;;

        *)
            log::error "Unknown archive file format: $3"

            return 1
    esac

    rm "$dest/$tempFile"
    bpm::fixPackageNesting "$dest"
}
