#!/usr/bin/env bash
# Finds a `bpm.ini` file in the current directory or any parent. When found,
# this will send the INI file location to the destination variable name.  The
# INI file location will be root-relative (you'll see `/folder/dir/bpm.ini`
# instead of `../bpm.ini`.
#
# Returns true (0) if `bpm.ini` was found.
bpm::findParentIni() {
    local result

    path::findParentContaining result -f "bpm.ini" || return 1

    local "${1-}" && assign::value "$1" "$result"
}
